"""
Repo client — create branch, commit workflow file, and open a Pull Request.
Uses PyGithub with the user's OAuth token (never the server's token).
"""

import re
import time
from github import Github, GithubException


def _parse_owner_repo(repo_url: str) -> tuple[str, str]:
    """Extract owner and repo name from a GitHub URL."""
    # Handle both https://github.com/owner/repo and https://github.com/owner/repo.git
    match = re.match(
        r"https?://github\.com/([^/]+)/([^/.]+)(?:\.git)?/?$",
        repo_url.strip(),
    )
    if not match:
        raise ValueError(f"Invalid GitHub repository URL: {repo_url}")
    return match.group(1), match.group(2)


def create_pr(
    token: str,
    repo_url: str,
    yaml_content: str,
    branch_name: str = "ci/add-pipeline",
) -> dict:
    """
    Create a new branch, commit the generated YAML as a workflow file,
    and open a Pull Request on the user's repository.

    Args:
        token: The user's GitHub OAuth access token.
        repo_url: Full GitHub repository URL.
        yaml_content: The generated YAML workflow content.
        branch_name: Name for the new branch.

    Returns:
        dict with pr_url and run_id (workflow run ID, may be None if not yet triggered).
    """
    owner, repo_name = _parse_owner_repo(repo_url)

    g = Github(token)
    repo = g.get_repo(f"{owner}/{repo_name}")

    # Get the default branch and its latest commit SHA
    default_branch = repo.default_branch
    default_ref = repo.get_git_ref(f"heads/{default_branch}")
    base_sha = default_ref.object.sha

    # Create a new branch from the default branch
    try:
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=base_sha,
        )
    except GithubException as e:
        if e.status == 422:
            # Branch already exists — update it instead
            existing_ref = repo.get_git_ref(f"heads/{branch_name}")
            existing_ref.edit(sha=base_sha, force=True)
        else:
            raise

    # Commit the workflow file to the new branch
    file_path = ".github/workflows/pipeline.yml"
    commit_message = "ci: add generated GitHub Actions pipeline"

    try:
        # Check if file already exists on the branch
        existing_file = repo.get_contents(file_path, ref=branch_name)
        repo.update_file(
            path=file_path,
            message=commit_message,
            content=yaml_content,
            sha=existing_file.sha,
            branch=branch_name,
        )
    except GithubException:
        # File doesn't exist yet — create it
        repo.create_file(
            path=file_path,
            message=commit_message,
            content=yaml_content,
            branch=branch_name,
        )

    # Build PR body with summary of the workflow
    pr_body = _build_pr_body(yaml_content)

    # Open a Pull Request
    try:
        pr = repo.create_pull(
            title="ci: add generated GitHub Actions pipeline",
            body=pr_body,
            head=branch_name,
            base=default_branch,
        )
    except GithubException as e:
        if e.status == 422:
            # PR already exists — find it
            pulls = repo.get_pulls(
                state="open", head=f"{owner}:{branch_name}", base=default_branch
            )
            pr = pulls[0] if pulls.totalCount > 0 else None
            if not pr:
                raise
        else:
            raise

    # Try to get the workflow run ID (may take a moment to trigger)
    run_id = _get_latest_run_id(repo, branch_name)

    return {
        "pr_url": pr.html_url,
        "run_id": str(run_id) if run_id else None,
    }


def _build_pr_body(yaml_content: str) -> str:
    """Build a descriptive PR body from the YAML content."""
    lines = []
    lines.append("## 🚀 Generated CI/CD Pipeline\n")
    lines.append("This PR was automatically generated by **PipelineGen**.\n")
    lines.append("### Checks included:\n")

    yaml_lower = yaml_content.lower()
    checks = []
    if "lint" in yaml_lower or "flake8" in yaml_lower or "eslint" in yaml_lower:
        checks.append("✅ Linting")
    if "test" in yaml_lower or "pytest" in yaml_lower or "jest" in yaml_lower:
        checks.append("✅ Tests")
    if "docker" in yaml_lower:
        checks.append("✅ Docker build")
    if "security" in yaml_lower or "trivy" in yaml_lower or "codeql" in yaml_lower:
        checks.append("✅ Security scan")
    if "cache" in yaml_lower:
        checks.append("✅ Dependency caching")
    if "deploy" in yaml_lower:
        checks.append("✅ Deploy (simulated)")

    if checks:
        lines.extend(f"- {c}" for c in checks)
    else:
        lines.append("- Custom workflow")

    lines.append("\n---")
    lines.append("*Review and merge this PR to enable CI/CD on your repository.*")

    return "\n".join(lines)


def _get_latest_run_id(repo, branch_name: str, max_retries: int = 3) -> int | None:
    """
    Try to find the latest workflow run triggered on the given branch.
    Retries a few times since GitHub may take a moment to start the run.
    """
    for attempt in range(max_retries):
        try:
            runs = repo.get_workflow_runs(branch=branch_name)
            if runs.totalCount > 0:
                return runs[0].id
        except GithubException:
            pass

        if attempt < max_retries - 1:
            time.sleep(2)

    return None
